### PR TITLE
eli-contrib week of 5 July

### LINKED ISSUE #3: filc crash on missing `cidlistsdir/` and `libp2p.key`
They should be automatically generated if not found

### PR DESCRIPTION
**Pull request by elijaharita**
All the changes are related to FILC:
- add 2 new CLI commands (`query-retrieval` and `retrieve`)
- move several hard-coded `"~/.filc"` strings into a CLI metadata entry
- create `~/.filc` directory if it doesn't exist (`0755` permission code, is this ok?)

fixes #3

### CODE REVIEW

File: filclient/filc/main.go [hunk 1]
```diff
@@ -43,9 +48,34 @@ func main() {
...
+	if err != nil {
+		fmt.Println("could not set config dir: ", err)
+	}
+	app.Metadata = map[string]interface{}{
+		"ddir": ddir,
+	}
+
+	// ...and make sure the directory exists
+	if err := os.MkdirAll(ddir, 0755); err != nil {
+		fmt.Println("could not create config directory: ", err)
```
Comment (whyrusleeping) [inline filclient/filc/main.go:62]: we might want to just exit the app here if this fails

**Review by whyrusleeping — APPROVED** [review]
Other than maybe wanting to return early if we fail to setup the homedir, this looks great! Thanks @elijaharita !

**Comment by elijaharita** [comment]
whoops, accident! fixed
